backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/images/uploads"

collections:
  - name: "team_members"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Job Role", name: "role", widget: "string", required: true }
      - { label: "Profile Image", name: "profile_image", widget: image }
  - name: "projects"
  label: "Projects"
  folder: "content/projects"
  create: true
  slug: "{{year}}--{{slug}}"
  fields: 
    - {label: "Project Name", name: "project_name", widget: "string", required: true}
    - {label: "Client Name", name: "client", widget: "string", required: true}